import { methodsFor } from '../utils/expenses';
import { Fragment, useState } from 'react';
import { Plus, SlidersHorizontal, Trash2, Share2, X } from 'lucide-react';
import Dialog from './Dialog';
import InfoTip from './InfoTip';
import DatePicker from './DatePicker';
import { emptyFilters, filterExpenses, filterError } from '../utils/filters';
import { newId } from '../utils/trips';

const splitLabels = { one: 'Only one person', two: 'Exactly two people', everyone: 'Everyone in the trip', none: 'No people selected', exact: 'Exactly', is: 'Includes any of', every: 'Includes all of', not: 'Excludes' };
const describe = rule => rule.field === 'splitWith' ? `Split with: ${splitLabels[rule.operator] || 'Includes'}${['exact', 'is', 'every', 'not'].includes(rule.operator) ? ' ' + (rule.values || []).join(', ') : ''}` : `${({ paidBy: 'Paid by', method: 'Method', description: 'Description', amount: 'Amount', date: 'Date' })[rule.field]}${rule.operator === 'not' ? ' excludes' : ''}: ${rule.values?.length ? rule.values.map(v => v || 'No method').join(', ') : rule.value || [rule.from || 'Any', rule.to || 'Any'].join(' – ')}`;
const fields = [['paidBy', 'Paid by'], ['splitWith', 'Split with'], ['method', 'Payment method'], ['description', 'Description'], ['amount', 'Amount'], ['date', 'Date']];
export default function FilterViews({ trip, views, activeId, onSelect, onSave, onRemove, onShare, toolbarActions }) {
  const [draft, setDraft] = useState(null);
  const [error, setError] = useState('');
  const active = views.find(v => v.id === activeId);
  const rules = draft?.filters.rules || [];
  const change = (id, updates) => setDraft(prev => ({ ...prev, filters: { ...prev.filters, rules: prev.filters.rules.map(r => r.id === id ? { ...r, ...updates } : r) } }));
  const add = field => setDraft(prev => ({ ...prev, filters: { ...prev.filters, rules: [...prev.filters.rules, { id: newId(), field, operator: field === 'splitWith' ? 'one' : 'is', values: [], value: '', from: '', to: '' }] } }));
  const choices = rule => rule.field === 'method' ? [...new Set([...trip.paymentMethods, ...trip.expenses.flatMap(methodsFor).filter(Boolean)]), ''] : trip.participants;
  return <><div className="view-toolbar expense-toolbar"><div className="view-tabs" role="tablist" aria-label="Expense views"><button role="tab" aria-selected={!activeId} className={!activeId ? 'active' : ''} onClick={() => onSelect(null)}>Expense log<span>{trip.expenses.length}</span></button>{views.map(view => <button role="tab" key={view.id} aria-selected={activeId === view.id} className={activeId === view.id ? 'active' : ''} onClick={() => onSelect(view.id)}>{view.name}<span>{filterExpenses(trip.expenses, view.filters, trip.participants).length}</span></button>)}<button className="new-view-button" aria-label="New view" title="New view" onClick={() => { setError(''); setDraft({ id: newId(), name: '', filters: { ...emptyFilters, rules: [] } }); }}><Plus size={17} /></button></div>{toolbarActions}</div>
    {active && <div className="view-actions"><button className="text-button" onClick={() => { setError(''); setDraft(structuredClone(active)); }}><SlidersHorizontal size={14} />Edit view</button><button className="button" onClick={onShare}><Share2 size={14} />Share view</button></div>}
    {active && <p className="view-caption">{(active.filters.rules || []).map(describe).join(active.filters.match === 'any' ? ' · OR · ' : ' · AND · ')} <InfoTip label="About filter views">Views only filter the log. Trip totals and settlements stay unchanged; editing a row edits the original expense.</InfoTip></p>}
    {draft && <Dialog wide title={views.some(v => v.id === draft.id) ? 'Edit filter view' : 'Create a filter view'} onClose={() => setDraft(null)}><form onSubmit={e => { e.preventDefault(); const issue = filterError(draft.filters); if (issue) { setError(issue); return; } setError(''); if (draft.name.trim()) { onSave({ ...draft, name: draft.name.trim() }); setDraft(null); } }}><div className="dialog-body form-stack"><label className="field">View name<input data-autofocus required maxLength={60} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="e.g. John · September" /></label><div className="filter-rules">{rules.map((rule, index) => <Fragment key={rule.id}>{index > 0 && <div className="filter-connector">{index === 1 ? <><select aria-label="Combine conditions" value={draft.filters.match || 'all'} onChange={e => setDraft({ ...draft, filters: { ...draft.filters, match: e.target.value } })}><option value="all">AND</option><option value="any">OR</option></select><InfoTip label="About AND and OR">AND requires every condition. OR requires at least one. This choice applies to all conditions in this view.</InfoTip></> : <span>{draft.filters.match === 'any' ? 'OR' : 'AND'}</span>}</div>}<div className="filter-rule"><div className="rule-heading"><strong>{fields.find(([id]) => id === rule.field)?.[1]}</strong>{['paidBy', 'splitWith', 'method', 'description'].includes(rule.field) && <select aria-label={`${rule.field} condition`} value={rule.operator} onChange={e => change(rule.id, { operator: e.target.value })}>{rule.field === 'splitWith' ? <><option value="one">Only one person</option><option value="two">Exactly two people</option><option value="everyone">Everyone in this trip</option><option value="none">No people selected</option><option value="exact">Exactly these people</option><option value="is">Includes any selected person</option><option value="every">Includes all selected people</option><option value="not">Excludes selected people</option></> : <><option value="is">{rule.field === 'description' ? 'contains' : 'is any of'}</option><option value="not">{rule.field === 'description' ? 'does not contain' : 'is none of'}</option></>}</select>}<button type="button" className="icon-button" aria-label={`Remove ${rule.field} condition`} onClick={() => setDraft({ ...draft, filters: { ...draft.filters, rules: rules.filter(r => r.id !== rule.id) } })}><X size={15} /></button></div>
      {rule.field === 'splitWith' && ['one', 'two', 'everyone', 'none'].includes(rule.operator) ? rule.operator === 'none' ? <InfoTip label="About empty splits">No selected split members. Each payer bears their own contribution.</InfoTip> : null : ['paidBy', 'splitWith', 'method'].includes(rule.field) ? <div className="rule-choices">{choices(rule).map(value => <label key={value} className={rule.values.includes(value) ? 'selected' : ''}><input type="checkbox" checked={rule.values.includes(value)} onChange={() => change(rule.id, { values: rule.values.includes(value) ? rule.values.filter(v => v !== value) : [...rule.values, value] })} />{value || 'No method'}</label>)}</div> : rule.field === 'description' ? <input aria-label="Description contains" placeholder="Enter text…" value={rule.value} onChange={e => change(rule.id, { value: e.target.value })} /> : rule.field === 'amount' ? <div className="form-grid"><label className="field">Minimum (₹)<input type="number" min="0" step="0.01" value={rule.from} onChange={e => change(rule.id, { from: e.target.value })} placeholder="No minimum" /></label><label className="field">Maximum (₹)<input type="number" min={rule.from || '0'} step="0.01" value={rule.to} onChange={e => change(rule.id, { to: e.target.value })} placeholder="No maximum" /></label></div> : <div className="form-grid"><div className="field">From<DatePicker value={rule.from} onChange={value => change(rule.id, { from: value })} /></div><div className="field">To<DatePicker align="right" value={rule.to} onChange={value => change(rule.id, { to: value })} /></div></div>}</div></Fragment>)}</div><label className="field">Add a condition<select aria-label="Add a condition" value="" onChange={e => { if (e.target.value) add(e.target.value); }}><option value="">Choose field…</option>{fields.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label>{error && <p className="error-message" role="alert">{error}</p>}<p className="filter-preview" role="status">{filterExpenses(trip.expenses, draft.filters, trip.participants).length} matching expenses</p></div><footer className="dialog-footer">{views.some(v => v.id === draft.id) && <button type="button" className="text-button danger footer-leading" onClick={() => { onRemove(draft.id); setDraft(null); }}><Trash2 size={14} />Remove view</button>}<button type="button" className="button" onClick={() => setDraft(null)}>Cancel</button><button type="submit" className="button primary">Save view</button></footer></form></Dialog>}
  </>;
}
