import InfoTip from './InfoTip';
import { sharedGroupId, recoveryLabel } from '../utils/workspace';
import { ChevronDown, ChevronRight, FolderOpen, History, Inbox, Link, Moon, PanelLeftClose, PanelLeftOpen, Plus, Receipt, ShieldCheck, Sun } from 'lucide-react';

export default function WorkspaceSidebar({ workspace, groups, collapsed, onCollapse, sections, onSections, theme, onThemeToggle, screen, incoming, activeTrip, onNavigate, onSelect, onSnapshot, onNew, onPaste, onRestore }) {
  const section = (key, label, Icon, count, children) => <section className="sidebar-section"><div className="sidebar-section-heading"><button className={`nav-item ${screen === key || (key === 'inbox' && incoming) ? 'active' : ''}`} title={label} aria-label={`${label} (${count})`} onClick={() => onNavigate(key)}><Icon size={18} /><span className="nav-label">{label}</span><span className="sidebar-count">{count}</span></button>{!collapsed && <button className="icon-button section-arrow" aria-label={`${sections[key] ? 'Collapse' : 'Expand'} ${label}`} aria-expanded={sections[key]} onClick={() => onSections({ ...sections, [key]: !sections[key] })}>{sections[key] ? <ChevronDown size={15} /> : <ChevronRight size={15} />}</button>}</div>{!collapsed && sections[key] && <div className="sidebar-section-items">{children}</div>}</section>;
  return <><div className="sidebar-brand-row"><button className="brand" aria-label="Split workspace" onClick={() => onNavigate('home')}><span className="brand-mark"><Receipt size={22} /></span>{!collapsed && <span>Split<span className="brand-dot">.</span></span>}</button><button className="icon-button sidebar-collapse" aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} onClick={onCollapse}>{collapsed ? <PanelLeftOpen size={18} /> : <PanelLeftClose size={18} />}</button></div><button className="button primary new-trip-button" title="New trip" aria-label="New trip" onClick={onNew}><Plus size={17} />{!collapsed && 'New trip'}</button><nav className="sidebar-section-scroll" aria-label="Workspace navigation">
    {section('home', 'My trips', FolderOpen, workspace.trips.length, workspace.trips.length ? workspace.trips.map(t => <button key={t.id} className={`trip-nav ${!incoming && screen === 'trip' && activeTrip?.id === t.id ? 'active' : ''}`} onClick={() => onSelect(t.id)}><span className="trip-dot" /><span>{t.name || 'Untitled trip'}</span></button>) : <p className="sidebar-empty">No trips yet.</p>)}
    {section('inbox', 'Shared with me', Inbox, groups.length, groups.length ? groups.map(({ id, latest: entry }) => <button key={id} className={`trip-nav ${incoming && sharedGroupId(incoming) === id ? 'active' : ''}`} onClick={() => onSnapshot(entry)}><span className="trip-dot" /><span>{entry.trip?.name || 'Untitled bill'}</span></button>) : <p className="sidebar-empty">No shared bills.</p>)}
    </nav><div className="sidebar-bottom"><button type="button" className="theme-control" role="switch" aria-label="Dark mode" aria-checked={theme === 'dark'} title={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'} onClick={onThemeToggle}>{theme === 'dark' ? <Moon size={17} /> : <Sun size={17} />}{!collapsed && <><span>Appearance</span><span className="theme-track" aria-hidden="true"><span className="theme-thumb" /></span></>}</button><button className="nav-item" title="Open a bill link" aria-label="Open a bill link" onClick={onPaste}><Link size={17} />{!collapsed && 'Open a bill link'}</button>{workspace.recovery && <button className="nav-item" title={recoveryLabel(workspace.recovery)} aria-label={recoveryLabel(workspace.recovery)} onClick={onRestore}><History size={17} />{!collapsed && recoveryLabel(workspace.recovery)}</button>}<div className="local-note">{!collapsed && <><ShieldCheck size={15} /><span>On this device</span></>}<InfoTip label="About local storage">Bills are saved in this browser, not in an account. Clearing browser data removes them. Shared links are snapshots, not live sync.</InfoTip></div></div></>;
}
